import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import Script from "next/script";
import "./globals.css";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import { PageTransition } from "@/components/page-transition";
import { ChatWidget } from "@/components/ChatWidget";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
const ibmPlexMono = IBM_Plex_Mono({
  weight: ["400", "500"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://verexa.ca"),
  title: {
    default:
      "Verexa Technologies | Premium Digital Solutions for GTA Businesses",
    template: "%s | Verexa Technologies",
  },
  description:
    "Empowering Canadian businesses with cutting-edge digital experiences. GTA-based technology company specializing in web, mobile, cloud & IT support.",
  keywords: [
    "Verexa Technologies",
    "Technology Company GTA",
    "Canadian Technology Company",
    "GTA Software Company",
    "Digital Solutions Ontario",
    "Small Business Tech Solutions Canada",
    "Startup Technology Partner Canada",
    // location
    "Managed IT Services Toronto",
    "Managed IT Services Mississauga",
    "Managed IT Services Brampton",
    "Managed IT Services Vaughan",
    "Managed IT Services Markham",
    "Managed IT Services Richmond Hill",
    "Managed IT Services Newmarket",
    "Managed IT Services Aurora",
    "Managed IT Services King",
    "Managed IT Services Whitchurch-Stouffville",
    "Managed IT Services East Gwillimbury",
    "Managed IT Services Georgina",
    "Managed IT Services Oakville",
    "Managed IT Services Burlington",
    "Managed IT Services Milton",
    "Managed IT Services Halton Hills",
    "Managed IT Services Oshawa",
    "Managed IT Services Pickering",
    "Managed IT Services Ajax",
    "Managed IT Services Whitby",
    "Managed IT Services Clarington",
    "Managed IT Services Brock",
    "Managed IT Services Scugog",
    "Managed IT Services Uxbridge",
    "IT support for small business GTA",
    "IT support for small business Toronto",
    "IT support for small business Mississauga",
    "IT support for small business Brampton",
    "IT support for small business Vaughan",
    "IT support for small business Markham",
    "IT support for small business Richmond Hill",
    "IT support for small business Newmarket",
    "IT support for small business Aurora",
    "IT support for small business King",
    "IT support for small business Whitchurch-Stouffville",
    "IT support for small business East Gwillimbury",
    "IT support for small business Georgina",
    "IT support for small business Oakville",
    "IT support for small business Burlington",
    "IT support for small business Milton",
    "IT support for small business Halton Hills",
    "IT support for small business Oshawa",
    "IT support for small business Pickering",
    "IT support for small business Ajax",
    "IT support for small business Whitby",
    "IT support for small business Clarington",
    "IT support for small business Brock",
    "IT support for small business Scugog",
    "IT support for small business Uxbridge",
    "Web design for small business GTA",
    "Web design for small business Toronto",
    "Web design for small business Mississauga",
    "Web design for small business Brampton",
    "Web design for small business Vaughan",
    "Web design for small business Markham",
    "Web design for small business Richmond Hill",
    "Web design for small business Newmarket",
    "Web design for small business Aurora",
    "Web design for small business King",
    "Web design for small business Whitchurch-Stouffville",
    "Web design for small business East Gwillimbury",
    "Web design for small business Georgina",
    "Web design for small business Oakville",
    "Web design for small business Burlington",
    "Web design for small business Milton",
    "Web design for small business Halton Hills",
    "Web design for small business Oshawa",
    "Web design for small business Pickering",
    "Web design for small business Ajax",
    "Web design for small business Whitby",
    "Web design for small business Clarington",
    "Web design for small business Brock",
    "Web design for small business Scugog",
    "Web design for small business Uxbridge",
    "Software development for small business GTA",
    "Software development for small business Toronto",
    "Software development for small business Mississauga",
    "Software development for small business Brampton",
    "Software development for small business Vaughan",
    "Software development for small business Markham",
    "Software development for small business Richmond Hill",
    "Software development for small business Newmarket",
    "Software development for small business Aurora",
    "Software development for small business King",
    "Software development for small business Whitchurch-Stouffville",
    "Software development for small business East Gwillimbury",
    "Software development for small business Georgina",
    "Software development for small business Oakville",
    "Software development for small business Burlington",
    "Software development for small business Milton",
    "Software development for small business Halton Hills",
    "Software development for small business Oshawa",
    "Software development for small business Pickering",
    "Software development for small business Ajax",
    "Software development for small business Whitby",
    "Software development for small business Clarington",
    "Software development for small business Brock",
    "Software development for small business Scugog",
    "Software development for small business Uxbridge",
    "Mobile app development for small business GTA",
    "Mobile app development for small business Toronto",
    "Mobile app development for small business Mississauga",
    "Mobile app development for small business Brampton",
    "Mobile app development for small business Vaughan",
    "Mobile app development for small business Markham",
    "Mobile app development for small business Richmond Hill",
    "Mobile app development for small business Newmarket",
    "Mobile app development for small business Aurora",
    "Mobile app development for small business King",
    "Mobile app development for small business Whitchurch-Stouffville",
    "Mobile app development for small business East Gwillimbury",
    "Mobile app development for small business Georgina",
    "Mobile app development for small business Oakville",
    "Mobile app development for small business Burlington",
    "Mobile app development for small business Milton",
    "Mobile app development for small business Halton Hills",
    "Mobile app development for small business Oshawa",
    "Mobile app development for small business Pickering",
    "Mobile app development for small business Ajax",
    "Mobile app development for small business Whitby",
    "Mobile app development for small business Clarington",
    "Mobile app development for small business Brock",
    "Mobile app development for small business Scugog",
    "Mobile app development for small business Uxbridge",
    "Cloud solutions for small business GTA",
    "Cloud solutions for small business Toronto",
    "Cloud solutions for small business Mississauga",
    "Cloud solutions for small business Brampton",
    "Cloud solutions for small business Vaughan",
    "Cloud solutions for small business Markham",
    "Cloud solutions for small business Richmond Hill",
    "Cloud solutions for small business Newmarket",
    "Cloud solutions for small business Aurora",
    "Cloud solutions for small business King",
    "Cloud solutions for small business Whitchurch-Stouffville",
    "Cloud solutions for small business East Gwillimbury",
    "Cloud solutions for small business Georgina",
    "Cloud solutions for small business Oakville",
    "Cloud solutions for small business Burlington",
    "Cloud solutions for small business Milton",
    "Cloud solutions for small business Halton Hills",
    "Cloud solutions for small business Oshawa",
    "Cloud solutions for small business Pickering",
    "Cloud solutions for small business Ajax",
    "Cloud solutions for small business Whitby",
    "Cloud solutions for small business Clarington",
    "Cloud solutions for small business Brock",
    "Cloud solutions for small business Scugog",
    "Cloud solutions for small business Uxbridge",
    "AI Automation for small business GTA",
    "AI Automation for small business Toronto",
    "AI Automation for small business Mississauga",
    "AI Automation for small business Brampton",
    "AI Automation for small business Vaughan",
    "AI Automation for small business Markham",
    "AI Automation for small business Richmond Hill",
    "AI Automation for small business Newmarket",
    "AI Automation for small business Aurora",
    "AI Automation for small business King",
    "AI Automation for small business Whitchurch-Stouffville",
    "AI Automation for small business East Gwillimbury",
    "AI Automation for small business Georgina",
    "AI Automation for small business Oakville",
    "AI Automation for small business Burlington",
    "AI Automation for small business Milton",
    "AI Automation for small business Halton Hills",
    "AI Automation for small business Oshawa",
    "AI Automation for small business Pickering",
    "AI Automation for small business Ajax",
    "AI Automation for small business Whitby",
    "AI Automation for small business Clarington",
    "AI Automation for small business Brock",
    "AI Automation for small business Scugog",
    "AI Automation for small business Uxbridge",
    "AI Chatbot development for small business GTA",
    "AI Chatbot development for small business Toronto",
    "AI Chatbot development for small business Mississauga",
    "AI Chatbot development for small business Brampton",
    "AI Chatbot development for small business Vaughan",
    "AI Chatbot development for small business Markham",
    "AI Chatbot development for small business Richmond Hill",
    "AI Chatbot development for small business Newmarket",
    "AI Chatbot development for small business Aurora",
    "AI Chatbot development for small business King",
    "AI Chatbot development for small business Whitchurch-Stouffville",
    "AI Chatbot development for small business East Gwillimbury",
    "AI Chatbot development for small business Georgina",
    "AI Chatbot development for small business Oakville",
    "AI Chatbot development for small business Burlington",
    "AI Chatbot development for small business Milton",
    "AI Chatbot development for small business Halton Hills",
    "AI Chatbot development for small business Oshawa",
    "AI Chatbot development for small business Pickering",
    "AI Chatbot development for small business Ajax",
    "AI Chatbot development for small business Whitby",
    "AI Chatbot development for small business Clarington",
    "AI Chatbot development for small business Brock",
    "AI Chatbot development for small business Scugog",
    "AI Chatbot development for small business Uxbridge",
    "AI Development for small business GTA",
    "AI Development for small business Toronto",
    "AI Development for small business Mississauga",
    "AI Development for small business Brampton",
    "AI Development for small business Vaughan",
    "AI Development for small business Markham",
    "AI Development for small business Richmond Hill",
    "AI Development for small business Newmarket",
    "AI Development for small business Aurora",
    "AI Development for small business King",
    "AI Development for small business Whitchurch-Stouffville",
    "AI Development for small business East Gwillimbury",
    "AI Development for small business Georgina",
    "AI Development for small business Oakville",
    "AI Development for small business Burlington",
    "AI Development for small business Milton",
    "AI Development for small business Halton Hills",
    "AI Development for small business Oshawa",
    "AI Development for small business Pickering",
    "AI Development for small business Ajax",
    "AI Development for small business Whitby",
    "AI Development for small business Clarington",
    "AI Development for small business Brock",
    "AI Development for small business Scugog",
    "AI Development for small business Uxbridge",
    // industry
    "Real Estate IT Support GTA",
    "Real Estate IT Support Toronto",
    "Real Estate IT Support Mississauga",
    "Real Estate IT Support Brampton",
    "Real Estate IT Support Vaughan",
    "Real Estate IT Support Markham",
    "Real Estate IT Support Richmond Hill",
    "Real Estate IT Support Newmarket",
    "Real Estate IT Support Aurora",
    "Real Estate IT Support King",
    "Real Estate IT Support Whitchurch-Stouffville",
    "Real Estate IT Support East Gwillimbury",
    "Real Estate IT Support Georgina",
    "Real Estate IT Support Oakville",
    "Real Estate IT Support Burlington",
    "Real Estate IT Support Milton",
    "Real Estate IT Support Halton Hills",
    "Real Estate IT Support Oshawa",
    "Real Estate IT Support Pickering",
    "Real Estate IT Support Ajax",
    "Real Estate IT Support Whitby",
    "Real Estate IT Support Clarington",
    "Real Estate IT Support Brock",
    "Real Estate IT Support Scugog",
    "Real Estate IT Support Uxbridge",
    "Legal IT Support GTA",
    "Legal IT Support Toronto",
    "Legal IT Support Mississauga",
    "Legal IT Support Brampton",
    "Legal IT Support Vaughan",
    "Legal IT Support Markham",
    "Legal IT Support Richmond Hill",
    "Legal IT Support Newmarket",
    "Legal IT Support Aurora",
    "Legal IT Support King",
    "Legal IT Support Whitchurch-Stouffville",
    "Legal IT Support East Gwillimbury",
    "Legal IT Support Georgina",
    "Legal IT Support Oakville",
    "Legal IT Support Burlington",
    "Legal IT Support Milton",
    "Legal IT Support Halton Hills",
    "Legal IT Support Oshawa",
    "Legal IT Support Pickering",
    "Legal IT Support Ajax",
    "Legal IT Support Whitby",
    "Legal IT Support Clarington",
    "Legal IT Support Brock",
    "Legal IT Support Scugog",
    "Legal IT Support Uxbridge",
    "Law Firm IT Support GTA",
    "Law Firm IT Support Toronto",
    "Law Firm IT Support Mississauga",
    "Law Firm IT Support Brampton",
    "Law Firm IT Support Vaughan",
    "Law Firm IT Support Markham",
    "Law Firm IT Support Richmond Hill",
    "Law Firm IT Support Newmarket",
    "Law Firm IT Support Aurora",
    "Law Firm IT Support King",
    "Law Firm IT Support Whitchurch-Stouffville",
    "Law Firm IT Support East Gwillimbury",
    "Law Firm IT Support Georgina",
    "Law Firm IT Support Oakville",
    "Law Firm IT Support Burlington",
    "Law Firm IT Support Milton",
    "Law Firm IT Support Halton Hills",
    "Law Firm IT Support Oshawa",
    "Law Firm IT Support Pickering",
    "Law Firm IT Support Ajax",
    "Law Firm IT Support Whitby",
    "Law Firm IT Support Clarington",
    "Law Firm IT Support Brock",
    "Law Firm IT Support Scugog",
    "Law Firm IT Support Uxbridge",
    "Accounting Firm IT Support GTA",
    "Accounting Firm IT Support Toronto",
    "Accounting Firm IT Support Mississauga",
    "Accounting Firm IT Support Brampton",
    "Accounting Firm IT Support Vaughan",
    "Accounting Firm IT Support Markham",
    "Accounting Firm IT Support Richmond Hill",
    "Accounting Firm IT Support Newmarket",
    "Accounting Firm IT Support Aurora",
    "Accounting Firm IT Support King",
    "Accounting Firm IT Support Whitchurch-Stouffville",
    "Accounting Firm IT Support East Gwillimbury",
    "Accounting Firm IT Support Georgina",
    "Accounting Firm IT Support Oakville",
    "Accounting Firm IT Support Burlington",
    "Accounting Firm IT Support Milton",
    "Accounting Firm IT Support Halton Hills",
    "Accounting Firm IT Support Oshawa",
    "Accounting Firm IT Support Pickering",
    "Accounting Firm IT Support Ajax",
    "Accounting Firm IT Support Whitby",
    "Accounting Firm IT Support Clarington",
    "Accounting Firm IT Support Brock",
    "Accounting Firm IT Support Scugog",
    "Accounting Firm IT Support Uxbridge",
    "Dental Clinic IT Support GTA",
    "Dental Clinic IT Support Toronto",
    "Dental Clinic IT Support Mississauga",
    "Dental Clinic IT Support Brampton",
    "Dental Clinic IT Support Vaughan",
    "Dental Clinic IT Support Markham",
    "Dental Clinic IT Support Richmond Hill",
    "Dental Clinic IT Support Newmarket",
    "Dental Clinic IT Support Aurora",
    "Dental Clinic IT Support King",
    "Dental Clinic IT Support Whitchurch-Stouffville",
    "Dental Clinic IT Support East Gwillimbury",
    "Dental Clinic IT Support Georgina",
    "Dental Clinic IT Support Oakville",
    "Dental Clinic IT Support Burlington",
    "Dental Clinic IT Support Milton",
    "Dental Clinic IT Support Halton Hills",
    "Dental Clinic IT Support Oshawa",
    "Dental Clinic IT Support Pickering",
    "Dental Clinic IT Support Ajax",
    "Dental Clinic IT Support Whitby",
    "Dental Clinic IT Support Clarington",
    "Dental Clinic IT Support Brock",
    "Dental Clinic IT Support Scugog",
    "Dental Clinic IT Support Uxbridge",
    "Medical IT Support GTA",
    "Medical IT Support Toronto",
    "Medical IT Support Mississauga",
    "Medical IT Support Brampton",
    "Medical IT Support Vaughan",
    "Medical IT Support Markham",
    "Medical IT Support Richmond Hill",
    "Medical IT Support Newmarket",
    "Medical IT Support Aurora",
    "Medical IT Support King",
    "Medical IT Support Whitchurch-Stouffville",
    "Medical IT Support East Gwillimbury",
    "Medical IT Support Georgina",
    "Medical IT Support Oakville",
    "Medical IT Support Burlington",
    "Medical IT Support Milton",
    "Medical IT Support Halton Hills",
    "Medical IT Support Oshawa",
    "Medical IT Support Pickering",
    "Medical IT Support Ajax",
    "Medical IT Support Whitby",
    "Medical IT Support Clarington",
    "Medical IT Support Brock",
    "Medical IT Support Scugog",
    "Medical IT Support Uxbridge",
    "Real Estate Website Design Toronto",
    "Real Estate Website Design Mississauga",
    "Real Estate Website Design Brampton",
    "Real Estate Website Design Vaughan",
    "Real Estate Website Design Markham",
    "Real Estate Website Design Richmond Hill",
    "Real Estate Website Design Newmarket",
    "Real Estate Website Design Aurora",
    "Real Estate Website Design King",
    "Real Estate Website Design Whitchurch-Stouffville",
    "Real Estate Website Design East Gwillimbury",
    "Real Estate Website Design Georgina",
    "Real Estate Website Design Oakville",
    "Real Estate Website Design Burlington",
    "Real Estate Website Design Milton",
    "Real Estate Website Design Halton Hills",
    "Real Estate Website Design Oshawa",
    "Real Estate Website Design Pickering",
    "Real Estate Website Design Ajax",
    "Real Estate Website Design Whitby",
    "Real Estate Website Design Clarington",
    "Real Estate Website Design Brock",
    "Real Estate Website Design Scugog",
    "Real Estate Website Design Uxbridge",
    "Restaurant Website Design Toronto",
    "Restaurant Website Design Mississauga",
    "Restaurant Website Design Brampton",
    "Restaurant Website Design Vaughan",
    "Restaurant Website Design Markham",
    "Restaurant Website Design Richmond Hill",
    "Restaurant Website Design Newmarket",
    "Restaurant Website Design Aurora",
    "Restaurant Website Design King",
    "Restaurant Website Design Whitchurch-Stouffville",
    "Restaurant Website Design East Gwillimbury",
    "Restaurant Website Design Georgina",
    "Restaurant Website Design Oakville",
    "Restaurant Website Design Burlington",
    "Restaurant Website Design Milton",
    "Restaurant Website Design Halton Hills",
    "Restaurant Website Design Oshawa",
    "Restaurant Website Design Pickering",
    "Restaurant Website Design Ajax",
    "Restaurant Website Design Whitby",
    "Restaurant Website Design Clarington",
    "Restaurant Website Design Brock",
    "Restaurant Website Design Scugog",
    "Restaurant Website Design Uxbridge",
    "Law Firm Website Design Toronto",
    "Law Firm Website Design Mississauga",
    "Law Firm Website Design Brampton",
    "Law Firm Website Design Vaughan",
    "Law Firm Website Design Markham",
    "Law Firm Website Design Richmond Hill",
    "Law Firm Website Design Newmarket",
    "Law Firm Website Design Aurora",
    "Law Firm Website Design King",
    "Law Firm Website Design Whitchurch-Stouffville",
    "Law Firm Website Design East Gwillimbury",
    "Law Firm Website Design Georgina",
    "Law Firm Website Design Oakville",
    "Law Firm Website Design Burlington",
    "Law Firm Website Design Milton",
    "Law Firm Website Design Halton Hills",
    "Law Firm Website Design Oshawa",
    "Law Firm Website Design Pickering",
    "Law Firm Website Design Ajax",
    "Law Firm Website Design Whitby",
    "Law Firm Website Design Clarington",
    "Law Firm Website Design Brock",
    "Law Firm Website Design Scugog",
    "Law Firm Website Design Uxbridge",
    "Accounting Firm Website Design Toronto",
    "Accounting Firm Website Design Mississauga",
    "Accounting Firm Website Design Brampton",
    "Accounting Firm Website Design Vaughan",
    "Accounting Firm Website Design Markham",
    "Accounting Firm Website Design Richmond Hill",
    "Accounting Firm Website Design Newmarket",
    "Accounting Firm Website Design Aurora",
    "Accounting Firm Website Design King",
    "Accounting Firm Website Design Whitchurch-Stouffville",
    "Accounting Firm Website Design East Gwillimbury",
    "Accounting Firm Website Design Georgina",
    "Accounting Firm Website Design Oakville",
    "Accounting Firm Website Design Burlington",
    "Accounting Firm Website Design Milton",
    "Accounting Firm Website Design Halton Hills",
    "Accounting Firm Website Design Oshawa",
    "Accounting Firm Website Design Pickering",
    "Accounting Firm Website Design Ajax",
    "Accounting Firm Website Design Whitby",
    "Accounting Firm Website Design Clarington",
    "Accounting Firm Website Design Brock",
    "Accounting Firm Website Design Scugog",
    "Accounting Firm Website Design Uxbridge",
    "Dental Clinic Website Design Toronto",
    "Dental Clinic Website Design Mississauga",
    "Dental Clinic Website Design Brampton",
    "Dental Clinic Website Design Vaughan",
    "Dental Clinic Website Design Markham",
    "Dental Clinic Website Design Richmond Hill",
    "Dental Clinic Website Design Newmarket",
    "Dental Clinic Website Design Aurora",
    "Dental Clinic Website Design King",
    "Dental Clinic Website Design Whitchurch-Stouffville",
    "Dental Clinic Website Design East Gwillimbury",
    "Dental Clinic Website Design Georgina",
    "Dental Clinic Website Design Oakville",
    "Dental Clinic Website Design Burlington",
    "Dental Clinic Website Design Milton",
    "Dental Clinic Website Design Halton Hills",
    "Dental Clinic Website Design Oshawa",
    "Dental Clinic Website Design Pickering",
    "Dental Clinic Website Design Ajax",
    "Dental Clinic Website Design Whitby",
    "Dental Clinic Website Design Clarington",
    "Dental Clinic Website Design Brock",
    "Dental Clinic Website Design Scugog",
    "Dental Clinic Website Design Uxbridge",
    "Medical Website Design Toronto",
    "Medical Website Design Mississauga",
    "Medical Website Design Brampton",
    "Medical Website Design Vaughan",
    "Medical Website Design Markham",
    "Medical Website Design Richmond Hill",
    "Medical Website Design Newmarket",
    "Medical Website Design Aurora",
    "Medical Website Design King",
    "Medical Website Design Whitchurch-Stouffville",
    "Medical Website Design East Gwillimbury",
    "Medical Website Design Georgina",
    "Medical Website Design Oakville",
    "Medical Website Design Burlington",
    "Medical Website Design Milton",
    "Medical Website Design Halton Hills",
    "Medical Website Design Oshawa",
    "Medical Website Design Pickering",
    "Medical Website Design Ajax",
    "Medical Website Design Whitby",
    "Medical Website Design Clarington",
    "Medical Website Design Brock",
    "Medical Website Design Scugog",
    "Medical Website Design Uxbridge",
    "Corporate Website Design Toronto",
    "Corporate Website Design Mississauga",
    "Corporate Website Design Brampton",
    "Corporate Website Design Vaughan",
    "Corporate Website Design Markham",
    "Corporate Website Design Richmond Hill",
    "Corporate Website Design Newmarket",
    "Corporate Website Design Aurora",
    "Corporate Website Design King",
    "Corporate Website Design Whitchurch-Stouffville",
    "Corporate Website Design East Gwillimbury",
    "Corporate Website Design Georgina",
    "Corporate Website Design Oakville",
    "Corporate Website Design Burlington",
    "Corporate Website Design Milton",
    "Corporate Website Design Halton Hills",
    "Corporate Website Design Oshawa",
    "Corporate Website Design Pickering",
    "Corporate Website Design Ajax",
    "Corporate Website Design Whitby",
    "Corporate Website Design Clarington",
    "Corporate Website Design Brock",
    "Corporate Website Design Scugog",
    "Corporate Website Design Uxbridge",
    "SaaS Website Design Toronto",
    "SaaS Website Design Mississauga",
    "SaaS Website Design Brampton",
    "SaaS Website Design Vaughan",
    "SaaS Website Design Markham",
    "SaaS Website Design Richmond Hill",
    "SaaS Website Design Newmarket",
    "SaaS Website Design Aurora",
    "SaaS Website Design King",
    "SaaS Website Design Whitchurch-Stouffville",
    "SaaS Website Design East Gwillimbury",
    "SaaS Website Design Georgina",
    "SaaS Website Design Oakville",
    "SaaS Website Design Burlington",
    "SaaS Website Design Milton",
    "SaaS Website Design Halton Hills",
    "SaaS Website Design Oshawa",
    "SaaS Website Design Pickering",
    "SaaS Website Design Ajax",
    "SaaS Website Design Whitby",
    "SaaS Website Design Clarington",
    "SaaS Website Design Brock",
    "SaaS Website Design Scugog",
    "SaaS Website Design Uxbridge",
    "Ecommerce Website Design Toronto",
    "Ecommerce Website Design Mississauga",
    "Ecommerce Website Design Brampton",
    "Ecommerce Website Design Vaughan",
    "Ecommerce Website Design Markham",
    "Ecommerce Website Design Richmond Hill",
    "Ecommerce Website Design Newmarket",
    "Ecommerce Website Design Aurora",
    "Ecommerce Website Design King",
    "Ecommerce Website Design Whitchurch-Stouffville",
    "Ecommerce Website Design East Gwillimbury",
    "Ecommerce Website Design Georgina",
    "Ecommerce Website Design Oakville",
    "Ecommerce Website Design Burlington",
    "Ecommerce Website Design Milton",
    "Ecommerce Website Design Halton Hills",
    "Ecommerce Website Design Oshawa",
    "Ecommerce Website Design Pickering",
    "Ecommerce Website Design Ajax",
    "Ecommerce Website Design Whitby",
    "Ecommerce Website Design Clarington",
    "Ecommerce Website Design Brock",
    "Ecommerce Website Design Scugog",
    "Ecommerce Website Design Uxbridge",
    "Staff Augmentation Toronto",
    "Staff Augmentation Mississauga",
    "Staff Augmentation Brampton",
    "Staff Augmentation Vaughan",
    "Staff Augmentation Markham",
    "Staff Augmentation Richmond Hill",
    "Staff Augmentation Newmarket",
    "Staff Augmentation Aurora",
    "Staff Augmentation King",
    "Staff Augmentation Whitchurch-Stouffville",
    "Staff Augmentation East Gwillimbury",
    "Staff Augmentation Georgina",
    "Staff Augmentation Oakville",
    "Staff Augmentation Burlington",
    "Staff Augmentation Milton",
    "Staff Augmentation Halton Hills",
    "Staff Augmentation Oshawa",
    "Staff Augmentation Pickering",
    "Staff Augmentation Ajax",
    "Staff Augmentation Whitby",
    "Staff Augmentation Clarington",
    "Staff Augmentation Brock",
    "Staff Augmentation Scugog",
    "Staff Augmentation Uxbridge",
    "Staff Augmentation Services",
    "Staff Augmentation Company",
    "Staff Augmentation Agency",
    "Staff Augmentation Toronto Area",
  ],
  authors: [{ name: "Verexa Technologies" }],
  creator: "Verexa Technologies",
  publisher: "Verexa Technologies",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: "Verexa Technologies | Premium Digital Solutions for GTA Businesses",
    description:
      "Empowering Canadian businesses with cutting-edge digital experiences. GTA-based technology company specializing in web, mobile, cloud & IT support.",
    url: "https://verexa.ca",
    siteName: "Verexa Technologies",
    images: [
      {
        url: "https://verexa.ca/banner.png",
        width: 1200,
        height: 630,
        alt: "Verexa Technologies Banner",
      },
    ],
    locale: "en_CA",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Verexa Technologies | Digital Solutions",
    description:
      "Empowering Canadian businesses with cutting-edge digital experiences. GTA-based. Canada-focused.",
    images: ["https://verexa.ca/banner.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon-16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overscroll-none cursor-none overflow-x-hidden">
      <head>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-0G8RVCC870"
          strategy="lazyOnload"
        />
        <Script id="google-analytics" strategy="lazyOnload">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-0G8RVCC870');
          `}
        </Script>
      </head>
      <body
        className={`${inter.variable} ${ibmPlexMono.variable} font-sans antialiased bg-background text-foreground`}
      >
        <SmoothCursor />
        <PageTransition>{children}</PageTransition>
        <ChatWidget />
        <Analytics />
      </body>
    </html>
  );
}
